In [1]:
import matplotlib
import scipy.io as sio
%matplotlib inline
import seaborn as sns
sns.set()
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold as SKF
from sklearn.linear_model import LogisticRegression as LR
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score as AUC
from sklearn.model_selection import train_test_split
import pylab as plt
from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from pandas.api.types import is_string_dtype, is_numeric_dtype
from sklearn.ensemble import _forest as forest
from sklearn.tree import export_graphviz

In [2]:
#loading test and train data
def load_data(data_folder, filename, Xdata_label, ydata_label):

    total_sections = 5
    X_train_og = np.array([]) 
    y_train_og = np.array([])
    for i in range(total_sections):
        train_fn = filename+str(i+1)+'_'+str(total_sections)+'.mat'
        trainmat = sio.loadmat(data_folder+train_fn)
        if X_train_og.shape[0] == 0:
            X_train_og = np.array(trainmat[Xdata_label])
            y_train_og = np.array(trainmat[ydata_label]).T
        else:
            curr_X_train = np.array(trainmat[Xdata_label])
            curr_y_train = np.array(trainmat[ydata_label]).T
            X_train_og = np.concatenate([X_train_og, curr_X_train], axis=0)
            y_train_og = np.concatenate([y_train_og, curr_y_train], axis=0)
    return X_train_og, y_train_og


In [3]:
All_Shapes=['Buckle-FL', 'Buckle', 'EP', 'HelT-FL', 'HelT', 'MGW-FL', 'MGW',
              'Opening-FL', 'Opening', 'ProT-FL', 'ProT', 'Rise-FL', 'Rise', 'Roll-FL',
              'Roll', 'Shear-FL', 'Shear', 'Shift-FL', 'Shift', 'Slide-FL', 'Slide',
              'Stagger-FL', 'Stagger', 'Stretch-FL', 'Stretch', 'Tilt-FL', 'Tilt']
print(len(All_Shapes))

27


In [4]:
data_folder = '/Users/yibeijia/Downloads/nucleosome_occupancy/data/train_test_data/'
# cluster_num=1
train_filename = 'yeastAll_Shapes_Train_5seqsPerClustr_'
X_train_og, y_train_og = load_data(data_folder, train_filename, 'Train_data', 'Train_labels')

In [5]:
test_filename = 'yeastAll_Shapes_Test_5seqsPerClustr_'
X_test_og, y_test_og = load_data(data_folder, test_filename, 'Test_data', 'Test_labels')

In [6]:
X_train_np = np.array(X_train_og)
X_test_np = np.array(X_test_og)

In [7]:
print(X_test_np.shape)
print(X_train_np.shape)

(129525, 146, 42)
(194305, 146, 42)


In [8]:
Shapes=['Buckle-FL', 'Buckle', 'EP', 'HelT-FL', 'HelT', 'MGW-FL', 'MGW', 
            'Opening-FL', 'Opening', 'ProT-FL', 'ProT', 'Rise-FL', 'Rise', 'Roll-FL',
            'Roll', 'Shear-FL', 'Shear', 'Shift-FL', 'Shift', 'Slide-FL', 'Slide', 
            'Stagger-FL', 'Stagger', 'Stretch-FL', 'Stretch', 'Tilt-FL', 'Tilt']

bp_Shapes=['Buckle-FL', 'Buckle', 'EP', 'MGW', 'MGW-FL', 'Opening-FL', 'Opening', 
           'ProT-FL', 'ProT', 'Rise-FL', 'Shear', 'Stagger-FL', 'Stagger', 
           'Stretch-FL', 'Stretch']

All_Shapes=[]
for shape in Shapes:
    if shape in bp_Shapes:
        All_Shapes.append(shape + '-F')
        All_Shapes.append(shape + '-B')
    else:
        All_Shapes.append(shape)
        
# for shape in bs_Shapes:
#     All_Shapes.append(shape)

print(len(All_Shapes))
print(All_Shapes)

42
['Buckle-FL-F', 'Buckle-FL-B', 'Buckle-F', 'Buckle-B', 'EP-F', 'EP-B', 'HelT-FL', 'HelT', 'MGW-FL-F', 'MGW-FL-B', 'MGW-F', 'MGW-B', 'Opening-FL-F', 'Opening-FL-B', 'Opening-F', 'Opening-B', 'ProT-FL-F', 'ProT-FL-B', 'ProT-F', 'ProT-B', 'Rise-FL-F', 'Rise-FL-B', 'Rise', 'Roll-FL', 'Roll', 'Shear-FL', 'Shear-F', 'Shear-B', 'Shift-FL', 'Shift', 'Slide-FL', 'Slide', 'Stagger-FL-F', 'Stagger-FL-B', 'Stagger-F', 'Stagger-B', 'Stretch-FL-F', 'Stretch-FL-B', 'Stretch-F', 'Stretch-B', 'Tilt-FL', 'Tilt']


In [9]:
print(len(X_test_np))
print(len(X_test_np[0]))
print(len(X_test_np[0][0]))


129525
146
42


In [10]:
for i in X_test_np[0]:
    print(i)
    print(len(i))
# for i in X_train_np:
#     print(i)

[ 7.15470e+00  8.89170e+00 -9.17000e-01  2.69860e+00 -5.55870e+00
 -6.99140e+00  3.38960e+00  3.11584e+01  1.01820e+00  1.00020e+00
  4.83300e+00  5.34160e+00  2.40990e+00  3.92680e+00  3.65100e-01
 -8.45200e-01  5.85680e+00  5.97220e+00 -3.58720e+00 -7.51360e+00
  2.62800e-01  3.40650e+00  4.85670e+00 -2.52250e+00  2.48800e-01
  2.55700e-01  3.03600e-01 -1.27400e-01  4.41800e-01 -2.45700e-01
  3.88200e-01 -1.73190e+00  2.85900e-01  3.63900e-01  7.37000e-02
 -1.98700e-01  1.23500e-01  1.31100e-01 -2.37000e-02 -2.37000e-02
  3.15650e+00  2.55560e+00]
42
[ 8.89170e+00  7.80260e+00  2.69860e+00 -4.66790e+00 -6.99140e+00
 -5.00690e+00  3.88610e+00  3.49074e+01  1.00020e+00  1.03240e+00
  5.34160e+00  5.41790e+00  3.92680e+00  2.18290e+00 -8.45200e-01
  5.45200e-01  5.97220e+00  5.87200e+00 -7.51360e+00 -6.64360e+00
  3.34900e-01  3.42200e+00  5.81750e+00  4.94020e+00  2.55700e-01
  2.50200e-01 -1.27400e-01 -2.84500e-01  5.15700e-01  2.72900e-01
  4.55700e-01 -1.46240e+00  3.63900e-01  2.93

  3.69920e+00  8.08000e-02]
42
[ 7.91020e+00  8.44730e+00 -1.24640e+00 -2.07440e+00 -5.00170e+00
 -8.00230e+00  4.06020e+00  3.57985e+01  9.75800e-01  1.05230e+00
  5.31740e+00  4.72480e+00  2.14770e+00  3.69890e+00  3.93800e-01
 -9.43800e-01  5.72840e+00  5.65540e+00 -6.55200e+00 -1.03941e+01
  2.91000e-01  3.39560e+00  4.85670e+00 -4.13300e-01  2.41000e-01
  2.44600e-01 -2.76700e-01  1.04000e-01  4.68500e-01 -2.65600e-01
  4.57300e-01 -1.47840e+00  2.93500e-01  3.44300e-01 -4.14000e-02
 -2.75200e-01  1.13000e-01  1.19600e-01 -4.39000e-02 -2.57000e-02
  3.72940e+00  1.87010e+00]
42
[ 8.44730e+00  7.46640e+00 -2.07440e+00  3.34110e+00 -8.00230e+00
 -8.45070e+00  3.82580e+00  3.54878e+01  1.05230e+00  1.17470e+00
  4.72480e+00  4.45330e+00  3.69890e+00  3.70650e+00 -9.43800e-01
 -1.02900e+00  5.65540e+00  6.06310e+00 -1.03941e+01 -9.70070e+00
  2.53100e-01  3.16430e+00  4.97630e+00 -3.21190e+00  2.44600e-01
  2.50000e-01  1.04000e-01  1.48700e-01  4.77500e-01 -8.99000e-02
  4.21500e-01 

[ 6.8097  6.8402  1.4518 -0.2353 -4.6113 -4.0335  3.7932 33.7208  0.9386
  0.9361  5.4278  5.1174  2.0316  2.0456  0.1342  0.2682  5.5601  5.2345
 -3.33   -3.2938  0.2478  3.3313  4.604  -2.3549  0.2505  0.2418 -0.2712
 -0.2738  0.4022  0.0979  0.426  -1.7104  0.2706  0.2697  0.13    0.0853
  0.1149  0.1204 -0.038  -0.0392  3.1641  0.4091]
42
[ 6.84020e+00  6.94510e+00 -2.35300e-01 -5.16400e-01 -4.03350e+00
 -4.81490e+00  3.86530e+00  3.64437e+01  9.36100e-01  9.35100e-01
  5.11740e+00  5.74660e+00  2.04560e+00  2.03820e+00  2.68200e-01
  1.90800e-01  5.23450e+00  5.40050e+00 -3.29380e+00 -3.80380e+00
  2.10800e-01  3.38430e+00  4.31050e+00 -1.87540e+00  2.41800e-01
  2.49200e-01 -2.73800e-01  2.50400e-01  4.24200e-01 -3.14000e-02
  4.10000e-01 -1.54710e+00  2.69700e-01  2.75200e-01  8.53000e-02
  1.42500e-01  1.20400e-01  1.20300e-01 -3.92000e-02 -4.01000e-02
  3.10270e+00 -4.56100e-01]
42
[ 6.94510e+00  8.01310e+00 -5.16400e-01  3.95350e+00 -4.81490e+00
 -6.76630e+00  3.86230e+00  3.

  3.47780e+00 -1.91270e+00]
42
[ 6.93380e+00  7.38400e+00 -2.54720e+00 -6.58990e+00 -5.45180e+00
 -7.61440e+00  3.35990e+00  3.22576e+01  1.03340e+00  1.00240e+00
  4.85170e+00  5.01070e+00  2.12160e+00  3.61820e+00  2.68900e-01
 -1.04320e+00  5.62990e+00  5.59590e+00 -3.23130e+00 -8.27240e+00
  3.00700e-01  3.39420e+00  4.86550e+00 -1.24930e+00  2.47400e-01
  2.50100e-01  2.76300e-01 -1.37000e-01  4.58900e-01 -2.77300e-01
  3.88800e-01 -1.84390e+00  2.84800e-01  3.12900e-01  7.98000e-02
  5.22000e-02  1.22000e-01  1.23700e-01 -2.90000e-02 -1.95000e-02
  3.22430e+00  1.97310e+00]
42
[ 7.38400e+00  8.02150e+00 -6.58990e+00  8.08200e-01 -7.61440e+00
 -7.22810e+00  3.79520e+00  3.48787e+01  1.00240e+00  1.02190e+00
  5.01070e+00  5.77020e+00  3.61820e+00  3.76850e+00 -1.04320e+00
 -1.11090e+00  5.59590e+00  5.83990e+00 -8.27240e+00 -1.06357e+01
  2.41200e-01  3.12250e+00  4.88890e+00 -2.89450e+00  2.50100e-01
  2.49900e-01 -1.37000e-01 -1.02800e-01  4.76900e-01  5.58000e-02
  4.07600e-01 

  3.58340e+00  3.04800e-01]
42
[ 8.14100e+00  7.46110e+00  3.22200e+00  6.00930e+00 -7.11490e+00
 -5.47830e+00  3.47800e+00  3.38429e+01  1.03300e+00  1.11630e+00
  5.54910e+00  5.42450e+00  3.69110e+00  2.19940e+00 -8.56400e-01
  4.39300e-01  5.53950e+00  6.13040e+00 -8.24410e+00 -7.39100e+00
  2.20400e-01  3.31850e+00  4.29100e+00 -1.70160e+00  2.49800e-01
  2.49800e-01  9.86000e-02  2.68300e-01  4.93100e-01  3.08700e-01
  3.82900e-01 -1.51330e+00  3.30600e-01  2.97100e-01  4.72000e-02
  5.69000e-02  1.16600e-01  1.15300e-01 -2.04000e-02 -3.90000e-02
  3.16450e+00 -7.64400e-01]
42
[  7.4611   8.5582   6.0093  -1.0874  -5.4783  -7.5148   3.8334  34.8668
   1.1163   1.004    5.4245   5.171    2.1994   3.6678   0.4393  -1.0495
   6.1304   5.7395  -7.391  -10.255    0.3286   3.4955   5.4852   5.7467
   0.2498   0.2486   0.2683   0.0909   0.4955  -0.4717   0.477   -1.3851
   0.2971   0.3399   0.0569  -0.2813   0.1153   0.1169  -0.039   -0.0349
   3.5597   1.9603]
42
[ 8.55820e+00  7.38720

[ 8.80820e+00  8.93920e+00 -6.86440e+00  2.28900e-01 -9.66010e+00
 -7.69980e+00  3.82380e+00  3.55179e+01  1.20490e+00  1.14390e+00
  4.29880e+00  5.73520e+00  4.23500e+00  4.24650e+00 -1.87100e+00
 -1.16250e+00  6.33350e+00  6.21690e+00 -1.38913e+01 -1.07142e+01
  2.50400e-01  3.16530e+00  4.94140e+00 -2.19390e+00  2.55200e-01
  2.51200e-01 -1.65600e-01 -9.80000e-02  5.24900e-01  1.93600e-01
  4.44900e-01 -1.08850e+00  3.39600e-01  3.50300e-01 -9.41000e-02
 -1.60300e-01  1.13500e-01  1.10100e-01 -1.63000e-02 -1.93000e-02
  3.44070e+00  7.30600e-01]
42
[ 8.93920e+00  8.47410e+00  2.28900e-01 -1.13530e+00 -7.69980e+00
 -7.78580e+00  4.13380e+00  3.44333e+01  1.14390e+00  1.10190e+00
  5.73520e+00  5.55220e+00  4.24650e+00  3.93670e+00 -1.16250e+00
 -1.29060e+00  6.21690e+00  6.21050e+00 -1.07142e+01 -9.93010e+00
  3.17400e-01  3.39380e+00  6.19630e+00  6.90430e+00  2.51200e-01
  2.50400e-01 -9.80000e-02  1.09900e-01  5.48200e-01  3.25000e-02
  6.11500e-01 -1.21140e+00  3.50300e-01  3.52

[ 7.68870e+00  8.48380e+00 -6.41470e+00 -3.68960e+00 -5.30680e+00
 -6.88440e+00  3.45950e+00  3.35964e+01  1.09400e+00  9.64600e-01
  5.54080e+00  6.05050e+00  2.27870e+00  3.82080e+00  4.24900e-01
 -9.97500e-01  6.29050e+00  5.61330e+00 -8.02840e+00 -7.90700e+00
  2.15200e-01  3.31370e+00  4.28250e+00 -2.33580e+00  2.49800e-01
  2.50000e-01 -2.63700e-01 -1.02600e-01  4.98500e-01 -3.36800e-01
  3.86800e-01 -1.47050e+00  2.91400e-01  3.29500e-01  3.50000e-02
  2.38000e-02  1.19200e-01  1.22500e-01 -3.65000e-02 -3.36000e-02
  3.12830e+00  9.05500e-01]
42
[ 8.4838e+00  7.9003e+00 -3.6896e+00 -2.2334e+00 -6.8844e+00 -4.9620e+00
  3.9203e+00  3.4693e+01  9.6460e-01  1.0354e+00  6.0505e+00  5.8225e+00
  3.8208e+00  2.1725e+00 -9.9750e-01  2.8530e-01  5.6133e+00  5.8793e+00
 -7.9070e+00 -7.0559e+00  3.0680e-01  3.2806e+00  5.5814e+00  4.3292e+00
  2.5000e-01  2.5000e-01 -1.0260e-01 -2.6750e-01  5.1300e-01  3.3040e-01
  5.2880e-01 -1.1651e+00  3.2950e-01  3.0520e-01  2.3800e-02 -1.0200e-02
  1

 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42


In [29]:
import random

train_num = int(len(X_train_np)/1000)
test_num = int(len(X_test_np)/1000)

print(train_num)
print(test_num)

random.seed(41)
train_idx = random.sample(range(len(X_train_np)), train_num)
random.seed(40)
test_idx = random.sample(range(len(X_test_np)), test_num)

print(train_idx)
print(test_idx)

train_subset = X_train_np[train_idx]
test_subset = X_test_np[test_idx]

print(train_subset.shape.shape)
print(test_subset)

is_train_np = np.ones(len(train_subset))
is_test_np = np.zeros(len(test_subset))
print(is_train_np)
print(is_test_np)

194
129
[99882, 87090, 60481, 43525, 101090, 151503, 180914, 74306, 144981, 72557, 100543, 191790, 151107, 2445, 65292, 173429, 4806, 115184, 40645, 39278, 189574, 83593, 43911, 67505, 171613, 181194, 162732, 153036, 15597, 31409, 154076, 8652, 113402, 73881, 192631, 56589, 19062, 190378, 94425, 191978, 124567, 32768, 145552, 175623, 4859, 32444, 25870, 37640, 180578, 46594, 14032, 69877, 83309, 59065, 162503, 6835, 159437, 151463, 47733, 114005, 15044, 79014, 104714, 38248, 27973, 175022, 24515, 106742, 5636, 173890, 172093, 129306, 103500, 60398, 5679, 22512, 35376, 20412, 120171, 190896, 105340, 111585, 139541, 73333, 141501, 7364, 3735, 171735, 121568, 84376, 46223, 36388, 17230, 187748, 10379, 188809, 178796, 28660, 173147, 184853, 33464, 108333, 171819, 186085, 22365, 159660, 138664, 109676, 157607, 26077, 63374, 57831, 114658, 95209, 192261, 120494, 178245, 189277, 107639, 117968, 21756, 175253, 72336, 142115, 55451, 179864, 65232, 72603, 98893, 184561, 85390, 163233, 99565, 772

In [30]:
y = np.concatenate((is_train_np,is_test_np))
print(y)
x = np.concatenate((train_subset,test_subset))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [39]:
import sklearn
x_shuffled, y_shuffled = sklearn.utils.shuffle(x, y)
y_shuffled

array([1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 0.

In [49]:
print(x_shuffled[0])
newarr = x_shuffled.reshape(len(x_shuffled),len(x_shuffled[0])*len(x_shuffled[0][0]))
print(newarr.shape)

[[  8.1694   7.1472   0.8048 ...  -0.0222   3.4015  -1.1755]
 [  7.1472   7.6676  -1.9495 ...  -0.0114   3.0404   0.8875]
 [  7.6676   8.2712 -10.0559 ...  -0.0266   3.1692   1.5508]
 ...
 [  7.4918   8.2627  -2.6242 ...  -0.0305   3.2331   2.5277]
 [  8.2627   6.8622   3.5584 ...  -0.0377   3.5364  -2.436 ]
 [  6.8622   6.4482  -2.2618 ...  -0.0162   3.0282  -0.5864]]
(323, 6132)


In [13]:
# def set_rf_samples(n):
#     """ Changes Scikit learn's random forests to give each tree a random sample of
#     n random rows.
#     """
#     forest._generate_sample_indices = (lambda rs, n_samples:
#         forest.check_random_state(rs).randint(0, n_samples, n))
# def reset_rf_samples():
#     """ Undoes the changes produced by set_rf_samples.
#     """
#     forest._generate_sample_indices = (lambda rs, n_samples:
#         forest.check_random_state(rs).randint(0, n_samples, n_samples))

In [14]:
# set_rf_samples(600) 

In [50]:
m = RandomForestClassifier(n_jobs=-1,max_depth=5)

predictions = np.zeros(y.shape)

In [53]:
skf = SKF(n_splits=20, shuffle=True, random_state=100)
for fold, (train_idx, test_idx) in enumerate(skf.split(newarr, y)):
    
    X_train, X_test = newarr[train_idx], newarr[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
        
    m.fit(X_train, y_train)
    probs = m.predict_proba(X_test)[:, 1]
    predictions[test_idx] = probs

In [54]:
print('ROC-AUC for X and Z distributions:', AUC(y, predictions))


ROC-AUC for X and Z distributions: 0.46072085031567167


In [55]:
plt.figure(figsize=(20,10))
predictions_train = predictions[len(tst):] #filtering the actual training rows
weights = (1./predictions_train) - 1. 
weights /= np.mean(weights) # Normalizing the weights
plt.xlabel('Computed sample weight')
plt.ylabel('# Samples')
sns.distplot(weights, kde=False)


NameError: name 'tst' is not defined

<Figure size 1440x720 with 0 Axes>